import './globals.css'
import { Inter } from 'next/font/google'
import Cabecalho from "@/components/cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className="reset">
        <Cabecalho />
          {children}
        <Rodape />
      </body>
    </html>
  );
}